import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
WEWRITE MOBILE VERSION - OPTIMIZED FOR MOBILE DEVICES
*/
`;

// 构建移动端版本
async function buildMobile() {
  try {
    const result = await esbuild.build({
      banner: {
        js: banner,
      },
      entryPoints: ["mobile-main.ts"],
      bundle: true,
      external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins],
      format: "cjs",
      target: "es2018",
      logLevel: "info",
      sourcemap: false,
      treeShaking: true,
      outfile: "main.js",
      minify: false, // 不压缩，便于调试
      loader: {
        ".css": "text"
      },
    });
    
    console.log("Mobile build completed successfully!");
    return 0;
  } catch (error) {
    console.error("Mobile build failed:", error);
    return 1;
  }
}

// 执行构建
const exitCode = await buildMobile();
process.exit(exitCode);
