import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
MOBILE TEST VERSION
*/
`;

// 构建最小化测试版本
async function buildTestMobile() {
  try {
    const result = await esbuild.build({
      banner: {
        js: banner,
      },
      entryPoints: ["src/test-mobile.ts"],
      bundle: true,
      external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins],
      format: "cjs",
      target: "es2018",
      logLevel: "info",
      sourcemap: false,
      treeShaking: true,
      outfile: "test-mobile.js",
      minify: true,
      loader: {
        ".css": "text"
      },
    });
    
    console.log("Test mobile build completed successfully!");
    return 0;
  } catch (error) {
    console.error("Test mobile build failed:", error);
    return 1;
  }
}

// 执行构建
const exitCode = await buildTestMobile();
process.exit(exitCode);
